language: scala

env:
  - PATH="$HOME/bin:$PATH"

scala:
   - 2.10.2

before_install:
  - travis/install-rescala.sh
  - travis/install-lms.sh

script:
  - travis/build.sh
  - sbt compile
  - sbt test
